// product-seek-react/src/Pages/Dashboard/components/order/order.js
import React,{Component}  from 'react';
import {connect} from 'react-redux';
import * as actions from '../../../../store/actions/index'
import * as config from '../../../../baseURL';
import axios from '../../../../axios';
import Swal from 'sweetalert2';


class Order extends Component{
  state={
    loading:false,
  }
  componentDidMount(){
    this.props.loadOrders(this.props.user.id);
  }

  render(){

    const cancle = (id)=>{

      this.setState({
        loading:true
      })

       Swal.fire({
        title: 'Are you sure?',
        // text: "You won't be able to revert this!",
        icon: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#080808',
        cancelButtonColor: '#bcbcbc',
        confirmButtonText: 'Yes, logout !'
      }).then((result) => {
        if (result.isConfirmed) {
          
          axios.get('/order/cancle/'+id).then(()=>{
            this.props.loadOrders(this.props.user.id);

            this.setState({
              loading:false
            })

            Swal.fire({
              icon: 'success',
              title: 'order has been cancled'
            })
          })
        
        }
      })

    }

    return(
      <div className="container pt-4 pb-4">
        <div className="row ">
          <div className="col-md-12">
            <div className="card ">
              <div className="card-header">
                <h5 className="text-center"style={{fontWeight:"1000"}}>Orders</h5>
              </div>
              <div className="card-body table-responsive">
                <table className="table ">
                  <thead className="thead-dark">
                    <tr>
                      <th scope="col">Order no</th>
                      <th scope="col">Image</th>
                      <th scope="col">Name</th>
                      <th scope="col">Price</th>
                      <th scope="col">Quantity</th>
                      <th scope="col">Total</th>
                      <th scope="col">Status</th>
                      <th scope="col">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {this.props.orders.length?
                      this.props.orders.map(order =>{
                        return(
                          <tr key={order.id}>
                            <td>{order.order_no}</td>
                            <td className='wishlist-image'><img src={ config.BaseURL + (order.products.product_image[0])} alt=""/></td>
                            <td>{order.products.title}</td>
                            <td>Rs {order.products.price}</td>
                            <td>{order.quantity}</td>
                            <td>Rs{order.total}</td>
                            <td>{order.status}</td>
                            <td>
                            {order.status!=='Canceled'?
                              <button className='btn btn-danger' disable={this.state.loading? true : false} onClick={()=>cancle(order.id)}>Cancle</button>:
                              ""
                            }
                            </td>
                          </tr>
                        )
                      })
                      : 
                      <tr>
                      <td colSpan='7'>Sorry no orders have been made or everthing has been delivered!!</td>
                      </tr>
                    }
                    
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    )
  }
}

const mapStateToProps = state =>{
  return{
    authenticated:state.auth.authenticated,
    user:state.auth.user,
    orders:state.order.orders
  }
}

const mapDispatchToProps = dispatch =>{
  return{
    loadOrders:(userId)=>dispatch(actions.ORDER(userId))
  }
}

export default connect(mapStateToProps,mapDispatchToProps)(Order);

// product-seek-backend/resources/js/components/backend/order/Order.vue
<template>
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-12">
				<div class="row">
				
				</div>
			</div>

			<div class="card mt-2">
				<div class="card-header">
					<h4>Orders</h4>
				</div>
				<div class="card-body table-responsive p-0">
					<table class="table text-nowrap">
            <thead>
              <tr>
                <th>Order number</th>
                <th>Customer name</th>
                <th>Status</th>
                <th>Order date</th>
                <th>Total</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody v-if='loading'>
            	<tr>
            		<td colspan="6" >
            			<div class="loadingio-spinner-ellipsis-eucq25nkrmd">
            				<div class="ldio-a9gm1xgpeqf">
            					<div></div>
            					<div></div>
            					<div></div>
            					<div></div>
            					<div></div>
            				</div>
            			</div>
            		</td>
            	</tr>
          	</tbody>
						<tbody v-else>
            	<tr v-if='!ordersLength'>
          			<td colspan="6" >Sorry no orders are made!!</td>
            	</tr>
	
            	<tr v-for='o in orders.data' :key='o.id'>
            		<td>{{ o.order_no }}</td>
            		<td><span v-for='c in o.users_order' :key='c.id'>{{ c.name }}</span></td>
            		<td>
            			{{ o.status }}
            		</td>
            		<td>{{  o.created_at| myDate }}</td>
            		<td>$ {{ o.total }}</td>
            		<td>
            			<button class="btn btn-primary" @click='loadCurrentOrder(o.id)'>
            				<i class="fas fa-eye mr-1"></i>View Order
            			</button>
            		</td>
            	</tr>
            </tbody>
          </table>
        </div>
        <div class="card-footer">
					<pagination :data="orders" @pagination-change-page="getResults"></pagination>
				</div>
      </div>
    </div>

    <!-- model  -->
    <div class="modal fade" id="order_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
		  <div class="modal-dialog modal-lg" role="document"  >
		    <div class="modal-content" v-if='currentOrder'>
		      <div class="modal-header">
		        <h5 class="modal-title" id="exampleModalLabel">{{ currentOrder.order_no }}</h5>
		        <button type="button" class="close" @click='closeModal' aria-label="Close">
		          <span aria-hidden="true">&times;</span>
		        </button>
		      </div>
		      <form>
			      <div class="modal-body">
				      <div class="row">  
				        <div class="col-md-12">
				        	<h6> <b>Customer</b> <span v-for='c in currentOrder.users_order'>{{ c.name }}</span><hr></h6>
				        </div>
				      </div>

			        <div class="row">
			        	<div class="col-md-4">
			        		<label for="order-Status">Order Status</label>
			        		<div class="form-group">
			        			<select  v-model='form.status' class="form-control">
			        				<option value="Processing">Processing</option>
			        				<option value="On the way">On the way</option>
			        				<option value="Delivered">Delivered</option>
			        				<option value="Returned">Returned</option>
			        				<option value="Cancled">Cancled</option>
			        			</select>
			        		</div>
			        	</div>
			        </div>
			        <div class="col-md-12">
			        	<h5>Products <hr></h5>
			        	<div class="card mt-2">
									<div class="card-body table-responsive p-0">
										<table class="table text-nowrap">
					            <thead>
					              <tr>
					                <th>Product Image</th>
					                <th>Product</th>
					                <th>Price</th>
					                <th>Quantity</th>
					                <th>Total</th>
					              </tr>
					            </thead>
					            <tbody>
					            	<tr>
					            		<td>
					            			<img :src="currentOrder.products.product_image[0]" alt="" style="width: 50px">
					            		</td>
					            		<td>{{ currentOrder.products.title }}</td>
					            		<td>$ {{ currentOrder.products.price }} </td>
					            		<td>{{ currentOrder.quantity }}</td>
					            		<td>$ {{ currentOrder.total }}</td>
					            	</tr>
					            </tbody>	
					          </table>
					        </div>
					      </div>
			        </div>
			        	
			        
			      </div>
			      <div class="modal-footer">
			        <button type="button" class="btn btn-secondary" @click='closeModal'>Close</button>
			         <button type="button" class="btn btn-primary" @click='updateOrder(currentOrder.id)'>Update</button>
			      </div>
		      </form>
		    </div>
		  </div>
		</div>
    <!-- end model -->
	</div>
</template>
<script>
	export default{
		props:['admin_url'],
		data(){
			return{
				orders:{},
				ordersLength:'',
				loading:true,
				currentOrder:null,
				form:new Form({
					status:'',
				}),
			}
		},
		methods:{
			loadOrders(){
				axios.get(this.admin_url+'/orders/paginated_orders').then(({data})=>{
					this.orders=data
					this.ordersLength=this.orders.data.length
					this.loading=false
				}).catch((response)=>{
					if(response.message=='Request failed with status code 401'){
						location.reload()
					}
					this.loading=false
				});
			},
			getResults(page = 1) {
      	this.loading=true;
        axios.get(this.admin_url+'/orders/paginated_orders/?page=' + page)
        .then(response => {
            this.orders = response.data;
            this.loading=false;
        }).catch((response)=>{
					if(response.message=='Request failed with status code 401'){
						location.reload()
					}
					this.loading=false
				});
      },
      loadCurrentOrder(id){
      	this.loading=true;
      	let that=this;
      	axios.get(this.admin_url+'/orders/show/'+id).then(function(res){
      		that.currentOrder=res.data;
      		that.form.status=that.currentOrder.status
      		$('#order_modal').modal('show')
      		that.loading=false

      	}).catch((response)=>{
					if(response.message=='Request failed with status code 401'){
						location.reload()
					}
					this.loading=false
				});
      },
      updateOrder(id){
      	$('#order_modal').modal('hide')
      	this.loading=true
      	this.form.put(this.admin_url+'/orders/update/'+id).then(()=>{
      		Toast.fire({
            icon: 'success',
            title: 'Order Updated successfully'
          })
          this.loadOrders()
          this.loading=false
      	}).catch((response)=>{
					if(response.message=='Request failed with status code 401'){
						location.reload()
					}
					this.loading=false
				});
      },
      closeModal(){
      	$('#order_modal').modal('hide')
      }
		},

		created(){
			this.loadOrders();
		}
	}
</script>
